# The URL the site will be built for
base_url = "https://joelvonrotz.ch/"

title = "JvR"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
  {name = "tags", feed=false}, # you can have taxonomies with the same name in multiple languages
  {name = "categories", feed=false}
]

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = true

# Whether to include the RFC3339 datetime of the page in the search index
include_date = true
include_path = false

# Whether to include the rendered content of the page/section in the index
include_content = true

# At which code point to truncate the content to. Useful if you have a lot of pages and the index would
# become too big to load on the site. Defaults to not being set.
truncate_content_length = 100

index_format = "fuse_json" # or "fuse_javascript"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
insert_anchor_links = "right"

[extra]
# Put all your custom variables here
